---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: palisade-reinthal-me-tls
  namespace: cert-manager
spec:
  secretName: palisade-reinthal-me-tls
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.palisade.reinthal.me"
    - "palisade.reinthal.me"