---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hcloud-ccm
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.hetzner.cloud
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: hcloud-ccm
        namespace: kube-system
      interval: 12h
  values:
    env:
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hcloud-token
            key: token
    networking:
      enabled: true
      clusterCIDR: "10.244.0.0/16"