---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: default
spec:
  interval: 24h
  chart:
    spec:
      chart: reflector
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
      interval: 24h
  values:
    replicaCount: 1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 24h
  url: https://emberstack.github.io/helm-charts
