apiVersion: v1
kind: Namespace
metadata:
  name: github-runners
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-cache-pvc
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi 
  storageClassName: openebs-single-replica
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: github-runners
spec:
  interval: 24h
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: github-runners
spec:
  interval: 24h
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.23.7"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: github-runners
      interval: 24h
  values:
    replicaCount: 1
    webhookPort: 9443
    syncPeriod: 1m
    defaultScaleDownDelay: 5m
    enableLeaderElection: true

    authSecret:
      enabled: true
      create: false
      name: "controller-manager"

    image:
      repository: "summerwind/actions-runner-controller"
      actionsRunnerRepositoryAndTag: "summerwind/actions-runner:ubuntu-20.04"
      dindSidecarRepositoryAndTag: "docker:dind"
      pullPolicy: IfNotPresent

    serviceAccount:
      create: true

    certManagerEnabled: false

    logFormat: text

    githubWebhookServer:
      enabled: false
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  name: self-hosted-runner-deployment
  namespace: actions
spec:
  template:
    spec:
      labels:
        - k8s-runner
      image: "summerwind/actions-runner:ubuntu-20.04"
      repository: "reinthal/template" 
      resources:
        requests:
          cpu: 2000m
          memory: 2000Mi
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: github-cache-pvc
      containers:
        - name: runner
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
