apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  name: self-hosted-runner-deployment
  namespace: github-runners
spec:
  replicas: 3
  template:
    spec:
      labels:
        - k8s-runner
      image: "ghcr.io/reinthal/kubernetes-rollout/action-runner-nix:sha-2c3b0a1"
      repository: "reinthal/template"
      dockerEnabled: false
      dockerdWithinRunnerContainer: false
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 8
          memory: 10Gi
      volumes: []
