apiVersion: v1
kind: Namespace
metadata:
  name: github-runners
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-cache-fixed-pvc
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi 
  storageClassName: openebs-hostpath-fixed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-store-pvc
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Nix store can get large
  storageClassName: openebs-hostpath-fixed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-var-pvc
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Nix daemon state and profiles
  storageClassName: openebs-hostpath-fixed
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: github-runners
spec:
  interval: 24h
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: github-runners
spec:
  interval: 24h
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.23.7"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: github-runners
      interval: 24h
  values:
    replicaCount: 1
    webhookPort: 9443
    syncPeriod: 1m
    defaultScaleDownDelay: 5m
    enableLeaderElection: true

    authSecret:
      enabled: true
      create: false
      name: "controller-manager"

    image:
      repository: "summerwind/actions-runner-controller"
      actionsRunnerRepositoryAndTag: "ghcr.io/reinthal/kubernetes-rollout/action-runner-nix:sha-2c3b0a1"
      pullPolicy: IfNotPresent

    serviceAccount:
      create: true

    certManagerEnabled: false

    logFormat: text

    githubWebhookServer:
      enabled: false
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  name: self-hosted-runner-deployment
  namespace: actions
spec:
  template:
    spec:
      labels:
        - k8s-runner
      image: "ghcr.io/reinthal/kubernetes-rollout/action-runner-nix:sha-2c3b0a1"
      repository: "reinthal/template"
      dockerdWithinRunnerContainer: false
      resources:
        requests:
          cpu: 2000m
          memory: 2000Mi
      volumes:
        - name: nix-store
          persistentVolumeClaim:
            claimName: nix-store-pvc
        - name: nix-var
          persistentVolumeClaim:
            claimName: nix-var-pvc
      containers:
        - name: runner
          volumeMounts:
            - mountPath: /nix/store
              name: nix-store
            - mountPath: /nix/var
              name: nix-var
          env:
            - name: PATH
              value: "/home/runner/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$(PATH)"
            - name: NIX_REMOTE
              value: "daemon"
