---
apiVersion: v1
kind: Namespace
metadata:
  name: ballista
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale
      version: "1.82.5"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: tailscale-secret
            key: client-id
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: tailscale-secret
            key: client-secret
    operatorConfig:
      defaultTags:
        - "tag:k8s"
      logging: "info"
    proxyConfig:
      defaultTags: "tag:k8s"
      firewallMode: auto
    apiServerProxyConfig:
      mode: "false"
