#cloud-config
hostname: ${node_name}
fqdn: ${node_name}.reinthal.me
manage_etc_hosts: true

packages:
  - curl
  - wget
  - jq

runcmd:
  
  # Start Tailscale with auto-approval using auth key (if provided)
  - curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --auth-key=${tailscale_authkey} --hostname=${node_name} ${tailscale_extra_args}
  
